//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCfConsumer.MediaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MediaService.IMedia")]
    public interface IMedia {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedia/GetMediaName", ReplyAction="http://tempuri.org/IMedia/GetMediaNameResponse")]
        string GetMediaName();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMediaChannel : WCfConsumer.MediaService.IMedia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MediaClient : System.ServiceModel.ClientBase<WCfConsumer.MediaService.IMedia>, WCfConsumer.MediaService.IMedia {
        
        public MediaClient() {
        }
        
        public MediaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MediaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MediaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MediaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMediaName() {
            return base.Channel.GetMediaName();
        }
    }
}
